import importlib.util
spec = importlib.util.spec_from_file_location('test_sentiment','tests/test_sentiment.py')
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)
mod.test_positive_high()
mod.test_positive_mid()
mod.test_neutral()
mod.test_negative_high_conf()
mod.test_negative_mid_conf()
print('All assertions passed')
